### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by wtj0906** [RittmanResearch/maybrain#9]
When I ran "python guiTest.py":
======================================================================
ERROR: test_highlights (__main__.TestSequenceFunctions)
test the ability to highlight some part of a brain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "guiTest.py", line 32, in setUp
    self.app = gui.runGui()
  File "/home/Tianjie/maybrain-master/bin/gui/mayBrainGUI.py", line 539, in runGui
    ex = mayBrainGUI()
  File "/home/Tianjie/maybrain-master/bin/gui/mayBrainGUI.py", line 37, in __init__
    self.plot = mb.plotObj() # start plot object
AttributeError: 'module' object has no attribute 'plotObj'

======================================================================
ERROR: test_loadData (__main__.TestSequenceFunctions)
test inputting of basic data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "guiTest.py", line 32, in setUp
    self.app = gui.runGui()
  File "/home/Tianjie/maybrain-master/bin/gui/mayBrainGUI.py", line 539, in runGui
    ex = mayBrainGUI()
  File "/home/Tianjie/maybrain-master/bin/gui/mayBrainGUI.py", line 37, in __init__
    self.plot = mb.plotObj() # start plot object
AttributeError: 'module' object has no attribute 'plotObj'

----------------------------------------------------------------------
Ran 2 tests in 0.595s

FAILED (errors=2)

**Comment by rittman** [comment]
Many apologies for not getting back to you sooner about this, things have been a bit busy!

I'll have a look in to this for you.

**Comment by tjiagoM** [comment]
Developing of GUI is stopped, thus I'm closing this issue
